# Generated by Django 4.0.6 on 2022-07-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productoId', models.AutoField(primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True, null=True)),
                ('productoDescripcion', models.CharField(max_length=200)),
                ('productoPrecio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
