# Generated by Django 4.0.6 on 2022-08-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoriaId', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaNombre', models.CharField(max_length=200)),
                ('categoriaDescripcion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Preferencias',
            fields=[
                ('preferenciaId', models.AutoField(primary_key=True, serialize=False)),
                ('preferenciaNombre', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True, null=True)),
            ],
            options={
                'db_table': 'preferencias',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productoId', models.AutoField(primary_key=True, serialize=False)),
                ('productoNombre', models.CharField(max_length=200)),
                ('productoDescripcion', models.CharField(max_length=200)),
                ('productoPrecio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('productoImagen', models.TextField(default='https://www.google.com')),
                ('estado', models.BooleanField(default=True, null=True)),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductosCategoria', to='products.categorias')),
                ('preferenciaId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductosPreferencia', to='products.preferencias')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
