# Generated by Django 4.0.6 on 2022-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='productoImagen',
            field=models.TextField(default='https://www.google.com'),
        ),
    ]
