# Generated by Django 4.0.6 on 2022-07-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('fechaVencimiento', models.DateTimeField(db_column='fecha_vecimiento')),
                ('estado', models.CharField(choices=[('POR_HACER', 'POR_HACER'), ('HACIENDO', 'HACIENDO'), ('HECHO', 'HECHO')], default='POR_HACER', max_length=10)),
            ],
            options={
                'db_table': 'tareas',
                'ordering': ['-fechaVencimiento'],
            },
        ),
    ]
